AWSTemplateFormatVersion: 2010-09-09

Parameters:

  VpcStackName:
    Type: String
    Description: 'The name of the VPC stack on which to layer this template.'

Resources:

  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'DBSubnetGroup for use with databases'
      SubnetIds:
        - Fn::ImportValue:
            !Join
              - '-'
              - - !Ref VpcStackName
                - SubnetA
        - Fn::ImportValue:
            !Join
              - '-'
              - - !Ref VpcStackName
                - SubnetB
        - Fn::ImportValue:
            !Join
              - '-'
              - - !Ref VpcStackName
                - SubnetB
      Tags:
        - Key: Name
          Value:
            !Join
              - '_'
              - - !Ref AWS::StackName
                - Dbsng

  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 100
      DBInstanceClass: 'db.t2.medium'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue:
            !Join
              - '-'
              - - !Ref VpcStackName
                - OpenSg
      PubliclyAccessible: true
      DBInstanceIdentifier:
        !Join
          - '-'
          - - !Ref AWS::StackName
            - dbinstance
      Engine: postgres
      DBName: tutorialdb
      StorageType: gp2
      MasterUsername:     masteruser
      MasterUserPassword: masterpassword
      Tags:
        - Key: Name
          Value:
            !Join
              - '_'
              - - !Ref AWS::StackName
                - DbInstance

Outputs:

  DBSubnetGroupOutput:
    Description: 'The created DBSubnetGroup'
    Value: !Ref DBSubnetGroup
    Export:
      Name:
        !Join
          - '-'
          - - !Ref AWS::StackName
            - Dbsng

  Endpoint:
    Description: 'URL of the database host'
    Value:
      Fn::GetAtt: DBInstance.Endpoint.Address
    Export:
      Name:
        !Join
          - '-'
          - - !Ref AWS::StackName
            - Endpoint
